Build Bundestag.io-api action trigger verringert
demokratie-live/democracy-development pull request #444
Opened 2021-06-08 19:51 UTC by ManAnRuck

Derzeit läuft die action https://github.com/demokratie-live/democracy-development/blob/6039ba5e0ba32b7ae1aa90e64bf82d9e5ca8e64e/.github/workflows/bundestag.io-api--build-and-push.yaml zu oft. 
Hiermit läuft die action nur noch wenn sich auch innerhalb des Ordners `bundestag.io-api` eine Änderung passiert.

2021-06-09 22:22 UTC, roschaefer requested changes
![not sure](https://media.giphy.com/media/ANbD1CCdA3iI8/giphy.gif)

I'm not sure on this one. @ManAnRuck could you please check if pushing a git tag to the repo without changing `bundestag-io/` would push a docker image tag to dockerhub?

I'm going to request changes here because I assume it doesn't. Feel free to merge if it does.

One question: What's the motivation for this PR? Saving build minutes on Github actions?

2021-06-09 22:22 UTC, roschaefer commented on .github/workflows/bundestag.io-api--build-and-push.yaml
> +      - "bundestag.io-api/**"
Because we don't push docker images on pull requests, the sole purpose of the github action is to check if the docker image can be built. This result should not change if the build context (the files) of the docker image didn't change. So, I'm totally :ok: with that.

2021-06-09 22:22 UTC, roschaefer commented on .github/workflows/bundestag.io-api--build-and-push.yaml
> +      - "bundestag.io-api/**"
What if you push a git tag and you don't change the content of the folder? Would it still push to dockerhub?

2021-06-10 16:10 UTC, ManAnRuck commented on .github/workflows/bundestag.io-api--build-and-push.yaml
> +      - "bundestag.io-api/**"
ja vielleicht sollten wir erstmal das Verhalten welches wir uns wünsch definieren :D

1. build test – bei Änderung im Packet
2. build push
   - bei einem Tag
   - oder push auf master

Für eine Mischung zwischen automatisch bei Push auf master und zusätzlich per Tag sehe ich gerade keinen Anwendungsfall. Ich wäre denk ich für das eine oder andere. Was ich auch gerne vermeiden würde, wäre, dass eine action gestartet wird, obwohl kein Grund (keine Änderungen) vorhanden sind.

2021-06-10 16:49 UTC, roschaefer commented on .github/workflows/bundestag.io-api--build-and-push.yaml
> +      - "bundestag.io-api/**"
Na, doch, der Anwendungsfall ist doch, dass man manuell einen Tag auf einen commit pusht. Dann soll dieser git tag auch auf dockerhub als docker image tag gepushed werden.

2021-06-11 19:30 UTC, ManAnRuck commented on .github/workflows/bundestag.io-api--build-and-push.yaml
> +      - "bundestag.io-api/**"
# ☺️ good news:

der path filter wird für tags ignoriert.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

<img width="889" alt="Bildschirmfoto 2021-06-11 um 21 28 58" src="https://user-images.githubusercontent.com/2183135/121739608-28340800-cafc-11eb-9b62-30dac2a229ac.png">

2021-06-14 20:15 UTC, roschaefer commented on .github/workflows/bundestag.io-api--build-and-push.yaml
> +      - "bundestag.io-api/**"
OK! :+1:

2021-06-14 20:15 UTC, roschaefer approved these changes

2021-06-14 20:15 UTC, merged